### PR TITLE
Add API client to the Plugin context

### PR DESCRIPTION
**Pull request by zbarahal**
Add an API client object that can be accessed by importing the client.py file and using the api_client object. This api_client object is an instance of a SlackClient that can make API method calls. This allows a user to make Slack API calls while using the RTM bot functionality. 

An example is included in doc/example-plugins/print_active_users.py that on loading the bot, will print the active users in the chat by using the Slack API to get all users in the organization and then checking each users presence in the chat.

### CODE REVIEW

**Comment by haroldkyle** [comment]
+1 Good idea, this would be helpful.

**Comment by go717franciswang** [comment]
+1 Great idea. I need this feature to make direct channels from user ids.

**Comment by ryukinix** [comment]
NICE!

**Comment by zbarahal** [comment]
Are there any changes that need to be made to get this PR approved?

**Comment by philipyun103** [comment]
Are the any updates on this PR?  I would love to see this merged into the master

**Comment by ryukinix** [comment]
This repository apparently is without maintenance...

**Comment by jammons** [comment]
That's a bit of an exaggeration, but it's run by busy people unfortunately. I do my best to keep up with things, but am pretty far behind unfortunately.

I think the goal of this PR is good (making API requests available in the plugins), but the implementation doesn't work with the latest restructuring or the direction I want to take things to make it more modular, so have been working on a refactor to make it doable.

**Comment by philipyun103** [comment]
@jammons  I submitted PR #57 which does work with the current restructuring.  Can you take a look and see if it meets your requirements for modularity?

**Pull request closed without merging**
