### PR TITLE
Cleanup README formatting

### PR DESCRIPTION
**Pull request by bbriggs**
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
* [x] I've written tests to cover the new code and functionality included in this PR.
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

#### PR Summary

Cleans up some minor formatting stuff in the readme

### CODE REVIEW

**Comment by aoberoi** [comment]
@bbriggs looks great to me! would you mind signing the CLA?

**Comment by bbriggs** [comment]
I promise I did, but it doesn't seem to be going through. It was the google form, right?

**Comment by aoberoi** [comment]
at an earlier point, it was. we switched over to CLA assistant ~9 months ago, so we probably need your signature again (there was no way to import the google sheets data since we need github usernames now). would you mind signing again?

**Comment by bbriggs** [comment]
Okay, signed!

**Pull request merged**
