### PR TITLE
Allow environment variable configuration

### PR DESCRIPTION
**Pull request by JacobSanford**
This PR allows system environment variables to define configuration (as an alternative to reading configuration from a file)

This was done with the primary goal of allowing the service to run in a virtualized container (such as Heroku) without committing keys and config vars to the git repo.

 I have performed rudimentary tests and I do not believe this breaks backwards. I'm not sure if this fits in your vision for the framework but I figured I'd send it over.

### CODE REVIEW

**Comment by Yasumoto** [comment]
This seems fair, and will help enable flexibility in different environments. @JacobSanford if you [don't mind rebasing](https://github.com/slackhq/python-rtmbot/blob/master/rtmbot.py#L20) we'd be happy to take this PR!

**Comment by swarren83** [comment]
@JacobSanford I would like to see this PR merged, are you able to rebase this?  Or would you mind if I submit your work in a new PR?

**Comment by Roach** [comment]
@swarren83 @JacobSanford getting this merged is going to be a little tricky since the file these changes were made to has since been split into `core.py` and `run_rtmbot.py`

If someone wants to give applying these changes to those files a go, I can make sure to get this merged as soon as it's submitted.

**Comment by Roach** [comment]
Closing this as the SlackClient package has changed a bit. Will be handled in #89

**Pull request closed without merging**
