### PR TITLE
Fixed README section header rendering in GitHub.

### PR DESCRIPTION
**Pull request by todofixthis**
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've been mindful about doing atomic commits, adding documentation to my changes, not refactoring too much.
* [x] I've a descriptive title and added any useful information for the reviewer. Where appropriate, I've attached a screenshot and/or screencast (gif preferably).
* [ ] I've written tests to cover the new code and functionality included in this PR.
  * _Not applicable to this PR._
* [x] I've read, agree to, and signed the [Contributor License Agreement (CLA)](https://docs.google.com/a/slack-corp.com/forms/d/1q_w8rlJG_x_xJOoSUMNl7R35rkpA7N6pUkKhfHHMD9c/viewform).

#### PR Summary
The section headers in README.md did not render correctly in GitHub.  This PR fixes the formatting so that they render correctly.

### CODE REVIEW

**Comment by Roach** [comment]
@todofixthis Changes look good 👍 

Would you mind signing the CLA for this? I think we may have updated the CLA system while this branch was in flight. Once that's done, I can merge this.

**Comment by todofixthis** [comment]
All set!

**Comment by aoberoi** [comment]
@todofixthis sorry, we still don't see you on the list of signatures. are you sure you used the right link? it should be: https://cla-assistant.io/slackapi/python-rtmbot?pullRequest=78

**Comment by aoberoi** [comment]
@todofixthis change of heart?

**Pull request closed without merging**
